#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring --start --components=pkcs11 &
dunst &
xset r rate 240 50 &
xset s blank &
xset s 600 &
mpd &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom/picom.conf &
xwallpaper --zoom ~/.local/share/wallpapers/road985.jpg &
# xwallpaper --zoom ~/.local/share/wallpapers/dmbrghbw.jpg &
nm-applet &
# $HOME/.screenlayout/only-hdmi.sh &
~/.local/bin/lbnrunner &
~/.config/polybar/scripts/polybar-launch &

## Clipmemu start
# clipmenud &

bspc monitor -d 1 2 3 4 5

bspc config border_width			1
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true

bspc config focus_follows_pointer	true

bspc config normal_border_color "#313244"
bspc config focused_border_color "#838C9F"

# scrtchpad
bspc rule -a sp-cal sticky=on state=floating
bspc rule -a sp-lf sticky=on state=floating
bspc rule -a sp-mus sticky=on state=floating
bspc rule -a sp-nmtui sticky=on state=floating
bspc rule -a sp-plsmxr sticky=on state=floating
bspc rule -a sp-term sticky=on state=floating

# bspc rule -a "*" split_dir=east # always split vertical
bspc rule -a Arandr         state=floating center=on 
bspc rule -a Galculator     state=floating center=on 
bspc rule -a Gcolor3        state=floating center=on
bspc rule -a KeePassXC      state=floating center=on
bspc rule -a Lxappearance   state=floating center=on
bspc rule -a Pavucontrol    state=floating center=on
bspc rule -a Sxiv           state=floating center=on 
bspc rule -a Tilix          state=floating center=on
bspc rule -a XVkbd          state=floating center=on 
bspc rule -a Yad            state=floating center=on 
bspc rule -a pavucontrol    state=floating center=on 
bspc rule -a Emacs state=tiled center=true
bspc rule -a qimgv state=floating center=true
bspc rule -a xarchiver state=floating layer=normal center=true
bspc rule -a mpv state=tiled layer=normal center=true
bspc rule -a firefox-esr desktop='^2' follow=on
bspc rule -a gimp desktop='^8' follow=on
bspc rule -a obs desktop='^9' follow=on
bspc rule -a thunar desktop='^8' follow=on
bspc rule -a geany desktop='^4' follow=on
